name: Draw ZMK keymaps
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - 'config/*.keymap'
      - 'config/*.dtsi'
      - '.github/workflows/draw/config.yaml'

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: ".github/workflows/draw/config.yaml"
      output_folder: "svg"
      parse_args: ""  # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: ""   # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"
